pool:
  vmImage: 'ubuntu-latest'

variables:
  #https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads
  TC_VERSION: 10.2-2020.11
  RM_VERSION: 10-2020-q4-major

resources:
- repo: self
  clean: true

steps:
- checkout: self
  clean: true

- task: Docker@2
  displayName: login on docker hub
  inputs:
    command: login
    containerRegistry: docker-hub-gigi81

- task: Bash@3
  displayName: 'Check environment'
  inputs:
    targetType: inline
    script: |
     if [ -z "$TC_VERSION" ]
     then
         exit 1
     else
         echo "Building version $TC_VERSION"
     fi
     
- task: Docker@2
  displayName: base image build
  inputs:
    command: build
    repository: gigi81/azurecross
    dockerfile: base/Dockerfile
    buildContext: base
    tags: |
      base
      base-$(TC_VERSION)

- template: docker-build.yml
  parameters:
    arch: 'arm-none-eabi'

- template: docker-build.yml
  parameters:
    arch: 'arm-none-linux-gnueabihf'

- template: docker-build.yml
  parameters:
    arch: 'aarch64-none-linux-gnu'

- task: Docker@2
  displayName: Publish Docker Images to Docker Hub
  inputs:
    command: push
    repository: gigi81/azurecross
    tags: |
      arm-none-eabi
      arm-none-eabi-$(TC_VERSION)
      arm-none-linux-gnueabihf
      arm-none-linux-gnueabihf-$(TC_VERSION)
      aarch64-none-linux-gnu
      aarch64-none-linux-gnu-$(TC_VERSION)
