pool:
  vmImage: 'ubuntu-16.04'

variables:
  #https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads
  TC_VERSION: 8.3-2019.03

resources:
- repo: self
  clean: true

steps:
- checkout: self
  clean: true

#docker magic: https://github.com/multiarch/qemu-user-static
- script: docker run --rm --privileged multiarch/qemu-user-static:register --reset

- task: Docker@2
  displayName: login on docker hub
  inputs:
    command: login
    containerRegistry: docker-hub-gigi81

- task: Bash@3
  displayName: 'Check environment'
  inputs:
    targetType: inline
    script: |
     if [ -z "$TC_VERSION" ]
     then
         exit 1
     else
         echo "Building version $TC_VERSION"
     fi
     
- task: Docker@2
  displayName: base image build
  inputs:
    command: build
    repository: azurecross
    dockerfile: base/Dockerfile
    buildContext: base
    tags: |
      base
      base-$(TC_VERSION)
