version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
         name: base build
         working_directory: base
         command: |
           docker build -t gigi81/azurecross:base .
           docker save -o base.tar gigi81/azurecross:base
      - run:
         name: aarch64-linux-gnu build
         working_directory: aarch64-linux-gnu
         command: |
           docker build -t gigi81/azurecross:aarch64-linux-gnu .
           docker save -o aarch64-linux-gnu.tar gigi81/azurecross:aarch64-linux-gnu
      - persist_to_workspace:
         root: .
         paths:
            - ./base.tar
            - ./aarch64-linux-gnu.tar
  publish:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load archived Docker images
          command: |
            docker load -i /tmp/workspace/base.tar
            docker load -i /tmp/workspace/aarch64-linux-gnu.tar
      - run:
          name: Publish Docker Images to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push gigi81/azurecross:base
            docker push gigi81/azurecross:aarch64-linux-gnu

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
