version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
         name: base build
         working_directory: base
         command: |
           docker build -t gigi81/azurecross:base .
      - run:
         name: aarch64-linux-gnu build
         working_directory: aarch64-linux-gnu
         command: |
           docker build -t gigi81/azurecross:aarch64-linux-gnu .
  publish:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Images to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push gigi81/azurecross:base
            docker push gigi81/azurecross:aarch64-linux-gnu

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
